-- DROP DATABASE {{DB_NAME}};

CREATE DATABASE IF NOT EXISTS {{DB_NAME}};

USE {{DB_NAME}};

CREATE TABLE IF NOT EXISTS burgers (
    id INT NOT NULL AUTO_INCREMENT,
    burger_name VARCHAR(64) NOT NULL,
    devoured BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);
